export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const RESET_AUTHENTICATED = 'RESET_AUTHENTICATED';
export const SET_USER = 'SET_USER';
export const SET_ERROR = 'SET_ERROR';
export const SET_SELECTED_NAV_LINK = 'SET_SELECTED_NAV_LINK';
