default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: password

development:
  <<: *default
  database: atm_simulator_dev
  host: localhost

test:
  <<: *default
  database: atm_simulator_test
  host: localhost
